// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatikaSurvivor.Data;

#nullable disable

namespace PatikaSurvivor.Migrations
{
    [DbContext(typeof(PatikaDbContext))]
    partial class PatikaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatikaSurvivor.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(9322),
                            IsDeleted = false,
                            Name = "Ünlüler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(9552),
                            IsDeleted = false,
                            Name = "Gönüllüler"
                        });
                });

            modelBuilder.Entity("PatikaSurvivor.Models.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 27, DateTimeKind.Local).AddTicks(7372),
                            FirstName = "Acun",
                            IsDeleted = false,
                            LastName = "Ilıcalı"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4073),
                            FirstName = "Aleyna",
                            IsDeleted = false,
                            LastName = "Avcı"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4089),
                            FirstName = "Hadise",
                            IsDeleted = false,
                            LastName = "Açıkgöz"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4091),
                            FirstName = "Sertan",
                            IsDeleted = false,
                            LastName = "Bozkuş"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4092),
                            FirstName = "Özge",
                            IsDeleted = false,
                            LastName = "Açık"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4095),
                            FirstName = "Kıvanç",
                            IsDeleted = false,
                            LastName = "Tatlıtuğ"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4096),
                            FirstName = "Ahmet",
                            IsDeleted = false,
                            LastName = "Yılmaz"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4097),
                            FirstName = "Elif",
                            IsDeleted = false,
                            LastName = "Demirtaş"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4098),
                            FirstName = "Cem",
                            IsDeleted = false,
                            LastName = "Öztürk"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 12, 19, 11, 15, 18, 31, DateTimeKind.Local).AddTicks(4099),
                            FirstName = "Ayşe",
                            IsDeleted = false,
                            LastName = "Karaca"
                        });
                });

            modelBuilder.Entity("PatikaSurvivor.Models.Competitor", b =>
                {
                    b.HasOne("PatikaSurvivor.Models.Category", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PatikaSurvivor.Models.Category", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
